// <auto-generated />
namespace TcNoSorgulaWebApi_03_03_22.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changecolumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changecolumn));
        
        string IMigrationMetadata.Id
        {
            get { return "202203030714526_changecolumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
